const COPY = {
  en: { title: "Central post office", new: "New letter", search: "Search correspondence", all: "All", queued: "Queued", working: "Working", completed: "Completed", failed: "Needs attention", stopped: "Stopped", reassigned: "Reassigned", request: "Request", result: "Result delivery", reply: "Reply", processed: "Processed", delivery_failed: "Delivery failed", empty: "No correspondence yet", start: "Send a letter to an agent, or choose automatic routing. Replies and follow-ups stay together here.", recipient: "Recipient", auto: "Automatic assignment", capability: "Type of help", general: "General", coding: "Code / debugging", review: "Review", subject: "Subject", text: "Your letter", repo: "Repository (optional)", send: "Send letter", follow: "Add an instruction or follow-up", stop: "Stop this conversation", stopNote: "Stops queued work and further delivery. A turn already running may finish; its reply remains visible.", reassign: "Reassign queued letter", route: "Delivery route", participants: "Participants", activity: "Latest activity", agent: "Available agents", delivery: "Automatic delivery", live: "Running", offline: "Not reporting", offlineNote: "The Web delivery worker is not reporting. Letters can still be received; check the runner before expecting a reply.", rule: "direct", capabilityRule: "capability", fallback: "fallback", view: "Open conversation", count: "conversations", noSelection: "Select a conversation", paused: "Paused", idle: "Waiting for letters", updated: "Updated", legacy: "Earlier mailbox records", legacyNote: "Earlier requests and session records are retained in the original inbox.", unknown: "Unknown" },
  "zh-Hant": { title: "中央郵局", new: "撰寫信件", search: "搜尋信件與對話", all: "全部", queued: "待投遞", working: "處理中", completed: "已完成", failed: "需要處理", stopped: "已停止", reassigned: "已改派", request: "請求", result: "結果送達", reply: "回覆", processed: "已處理", delivery_failed: "投遞失敗", empty: "目前還沒有往返信件", start: "寄信給指定 agent，或交給郵局自動分派。回覆與追問會串在同一件事裡。", recipient: "收件者", auto: "自動分派", capability: "需要哪類協助", general: "一般協助", coding: "程式／除錯", review: "審查", subject: "主旨", text: "信件內容", repo: "專案路徑（選填）", send: "寄出信件", follow: "插話或追問", stop: "停止這件事", stopNote: "停止待處理信件與後續投遞。已在執行的一輪可能繼續完成，回覆仍會保留。", reassign: "改派待處理信件", route: "投遞路徑", participants: "參與者", activity: "最近活動", agent: "可收信的 agents", delivery: "自動投遞", live: "運作中", offline: "尚未回報", offlineNote: "Web 投遞程序尚未回報。郵局仍可收信；若沒有收到回覆，請檢查 runner。", rule: "指定收件者", capabilityRule: "依能力分派", fallback: "備援分派", view: "開啟對話", count: "件事", noSelection: "選擇一件事查看往返", paused: "已暫停", idle: "等待信件", updated: "更新時間", legacy: "先前的信件紀錄", legacyNote: "先前的請求與 session 紀錄仍保留在原收件匣。", unknown: "未知" },
};
function readableLetter(text, copy) {
  return String(text || "").replace(/(?:^|\n)```agent-mail[ \t]*\n([\s\S]*?)\n```[ \t]*$/, (block, json) => {
    try { const request = JSON.parse(json); return `\n${copy.request} → ${request.to || copy.auto}\n${request.text}`; }
    catch { return block; }
  });
}
const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const date = (value, locale) => `<time datetime="${escape(value)}">${escape(new Date(value).toLocaleString(locale === "zh-Hant" ? "zh-TW" : "en-GB", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }))}</time>`;

export function renderMail(data, locale) {
  const c = COPY[locale] || COPY.en;
  const { threads, current, agents, delivery } = data;
  const label = (state) => c[state] || state;
  const badge = (state) => `<span class="status ${escape(state)}">${escape(label(state))}</span>`;
  const options = (auto = true, selected = "any") => `${auto ? `<option value="any">${c.auto}</option>` : ""}${agents.map((a) => `<option value="${escape(a.name)}"${a.name === selected ? " selected" : ""}>${escape(a.name)} · ${escape(c[a.kind] || a.kind)}</option>`).join("")}`;
  const form = (follow = false) => `<form class="request-form postal-form" action="${follow ? `/api/mail/${encodeURIComponent(current.id)}/messages` : "/api/mail"}" method="post" data-success="mail">
    <div class="postal-fields"><label>${c.recipient}<select name="target">${options(true, follow ? current.letters[0].to : "any")}</select></label>${!follow ? `<label>${c.capability}<select name="capability"><option value="auto">${c.auto}</option>${["general", "coding", "review"].map((v) => `<option value="${v}">${c[v]}</option>`).join("")}</select></label>` : ""}</div>
    ${!follow ? `<label>${c.subject}<input name="subject" maxlength="120" autocomplete="off"></label>` : ""}
    <label>${follow ? c.follow : c.text}<textarea name="request" rows="${follow ? 4 : 9}" maxlength="16000" required></textarea></label>
    ${!follow ? `<label>${c.repo}<input name="repo" autocomplete="off"></label>` : ""}<button type="submit">${c.send}</button></form>`;
  const list = `<section class="postal-list" aria-label="${c.title}"><div class="postal-list-head"><b>${threads.length} ${c.count}</b><a href="/mail/new">＋ ${c.new}</a></div><label class="postal-search"><span class="sr-only">${c.search}</span><input type="search" placeholder="${c.search}" data-mail-search></label><div class="postal-filters" role="group" aria-label="${c.title}">${["all", "queued", "working", "failed", "completed"].map((v) => `<button type="button" data-mail-filter="${v}" aria-pressed="${v === "all"}">${c[v]}</button>`).join("")}</div><div class="postal-letters">${threads.map((thread) => `<a class="postal-letter${thread.id === current?.id ? " selected" : ""}" href="/mail/${encodeURIComponent(thread.id)}" data-mail-status="${escape(thread.status)}" data-mail-search-text="${escape(`${thread.subject} ${thread.participants.join(" ")} ${thread.summary}`.toLowerCase())}"><div class="row-title"><b>${escape(thread.from)}</b>${badge(thread.status)}</div><h3>${escape(thread.subject)}</h3><p>${escape(readableLetter(thread.summary, c).slice(0, 140))}</p><div class="postal-letter-foot"><span>${escape(thread.participants.join(" → "))}</span>${date(thread.updatedAt, locale)}</div></a>`).join("") || `<p class="empty">${c.empty}</p>`}</div><a class="postal-legacy" href="/inbox">${c.legacy} →</a></section>`;
  const reader = `<section class="postal-reader">${current ? `<div class="postal-subject"><p class="eyebrow">${c.view}</p><h2>${escape(current.subject)}</h2><div class="postal-meta">${badge(current.status)}<span>${escape(current.participants.join(" · "))}</span></div></div><div class="postal-timeline">${current.timeline.map((e) => `<article class="postal-event ${escape(e.type)}"><div class="postal-event-head"><span class="avatar">${escape((e.from || "AR").slice(0, 2).toUpperCase())}</span><div><b>${escape(e.from || "Agent River")}${e.to ? ` → ${escape(e.to)}` : ""}</b><small>${escape(label(e.type))}${e.status ? ` · ${escape(label(e.status))}` : ""}</small></div>${date(e.created_at, locale)}</div>${e.reason ? `<p class="postal-route">${c.route}: ${escape(e.reason.replace("direct:", `${c.rule}: `).replace("capability:", `${c.capabilityRule}: `).replace("fallback:", `${c.fallback}: `))}</p>` : ""}<pre class="postal-body">${escape(readableLetter(e.text, c))}</pre>${e.error ? `<p class="postal-error">${escape(e.error)}</p>` : ""}</article>`).join("")}</div>${!current.stopped ? form(true) : `<p class="postal-stop-note">${c.stopNote}</p>`}` : `<div class="postal-subject"><p class="eyebrow">${c.title}</p><h2>${c.new}</h2><p>${c.start}</p></div>${form()}`}</section>`;
  const info = `<aside class="postal-info"><section><h2>${c.delivery}</h2><p class="delivery-state ${delivery.fresh ? "live" : "offline"}"><span></span>${delivery.fresh ? c.live : c.offline}</p>${!delivery.fresh ? `<p>${c.offlineNote}</p>` : Object.entries(delivery.lanes).map(([name, lane]) => `<p><b>${escape(name)}</b> · ${escape(label(lane.status))}${lane.reason ? `<br><small>${escape(lane.reason)}</small>` : ""}${lane.error ? `<br><small>${escape(lane.error)}</small>` : ""}</p>`).join("")}</section><section><h2>${current ? c.participants : c.agent}</h2>${agents.filter((a) => !current || current.participants.includes(a.name)).map((a) => `<div class="postal-agent"><span class="avatar">${escape(a.name.slice(0, 2).toUpperCase())}</span><div><b>${escape(a.name)}</b><small>${escape(c[a.kind] || a.kind)} · ${escape(a.style)}</small></div></div>`).join("")}</section>${current ? `<section><h2>${c.activity}</h2>${date(current.updatedAt, locale)}${current.repo ? `<p class="postal-path">${escape(current.repo)}</p>` : ""}<small class="postal-path postal-id">${escape(current.id)}</small></section>${!current.stopped ? `<section><h2>${c.reassign}</h2>${current.letters.filter((m) => m.canReassign).map((m) => `<form class="request-form" action="/api/mail/letters/${encodeURIComponent(m.id)}/reassign" method="post" data-success="mail"><label>${escape(m.to)} · ${escape(m.text.slice(0, 45))}<select name="target">${options(false)}</select></label><button type="submit">${c.reassign}</button></form>`).join("")}<button type="button" class="action-button destructive" data-endpoint="/api/mail/${encodeURIComponent(current.id)}/stop" data-confirm="stop">${c.stop}</button><p>${c.stopNote}</p></section>` : ""}` : `<section><h2>${c.legacy}</h2><p>${c.legacyNote}</p><a href="/inbox">${c.legacy} →</a></section>`}</aside>`;
  return `<div class="post-office">${list}${reader}${info}</div>`;
}
